server.port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vdcom-test-task?serverTimezone=UTC
    username: root
    password: testtest
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 20
        order_inserts: true
        generate_statistics: true